version: "3.9"
services:
  speech_analyzer:
    build:
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "${SPEECH_ANALYZER_PORT}:${SPEECH_ANALYZER_PORT}"
    environment:
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - ELEVENLABS_API_KEY=$ELEVENLABS_API_KEY
    volumes:
      - ./app:/app
    command: >
      bash -c "uvicorn main:app
      --port $SPEECH_ANALYZER_PORT
      --host 0.0.0.0
      --reload"
    restart: always